In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# **⛏  how to find missing valu?**

# **Example 1**

In [1]:
import numpy as np
data = [[1,2,np.nan],
        [3,np.nan,1],
        [5,np.nan,0],
        [np.nan,4,np.nan ],
        [5,0,np.nan],
        [4,5,5]]
arr_data= np.array(data)

miss= np.isnan(arr_data)
print(miss)


[[False False  True]
 [False  True False]
 [False  True False]
 [ True False  True]
 [False False  True]
 [False False False]]


In [ ]:
import pandas as pd
arr_data= pd.DataFrame(arr_data)
arr_data

0    1    2
0  1.0  2.0  NaN
1  3.0  NaN  1.0
2  5.0  NaN  0.0
3  NaN  4.0  NaN
4  5.0  0.0  NaN
5  4.0  5.0  5.0

In [ ]:
### miss_arr= arr_data.isnull().sum().sort_values(ascending=False)

In [ ]:
miss_arr= arr_data.isnull()
miss_arr

0      1      2
0  False  False   True
1  False   True  False
2  False   True  False
3   True  False   True
4  False  False   True
5  False  False  False

In [ ]:
miss_arr.sum().sort_values(ascending=False)


2    3
1    2
0    1
dtype: int64

# **Example 2: zerooooooos**

In [ ]:
array= ([0,10,2,0],[0,0,4,6],[2,5,7,0],[4,55,0,8])
array= np.array(array)
array

array([[ 0, 10,  2,  0],
       [ 0,  0,  4,  6],
       [ 2,  5,  7,  0],
       [ 4, 55,  0,  8]])

In [ ]:
df_arr= pd.DataFrame(array)
df_arr

0   1  2  3
0  0  10  2  0
1  0   0  4  6
2  2   5  7  0
3  4  55  0  8

In [ ]:
from numpy import nan
###### Mark zeros as nan
df_arr= df_arr.replace(0, nan)
df_arr

0     1    2    3
0  NaN  10.0  2.0  NaN
1  NaN   NaN  4.0  6.0
2  2.0   5.0  7.0  NaN
3  4.0  55.0  NaN  8.0

In [ ]:
missing= df_arr.isnull().sum().sort_values(ascending=False)
missing

3    2
0    2
2    1
1    1
dtype: int64

# **Example 3: None**

In [ ]:
aaa= ([1, 2, None],[4,None,None])
aaa=np.array(aaa)
aaa

array([[1, 2, None],
       [4, None, None]], dtype=object)

In [ ]:
df_aaa=pd.DataFrame(aaa)
df_aaa

0     1     2
0  1     2  None
1  4  None  None

In [ ]:
df_aaa=df_aaa.fillna(np.nan)


df_aaa

0    1   2
0  1  2.0 NaN
1  4  NaN NaN

In [ ]:
miss_aaa= df_aaa.isnull().sum().sort_values(ascending=False)
miss_aaa

2    2
1    1
0    0
dtype: int64

# **Example 4:    '-'**

In [ ]:
bbb= ([1, 2, '-'],[4,'-','-'],[33,44,55])
bbb=np.array(bbb)
bbb

array([['1', '2', '-'],
       ['4', '-', '-'],
       ['33', '44', '55']], dtype='<U21')

In [ ]:
df_bbb= pd.DataFrame(bbb)
df_bbb

0   1   2
0   1   2   -
1   4   -   -
2  33  44  55

In [ ]:
df_bbb= df_bbb.replace('-', nan)
df_bbb

0    1    2
0   1    2  NaN
1   4  NaN  NaN
2  33   44   55

In [ ]:
miss_bbb= df_bbb.isnull().sum().sort_values(ascending=False)
miss_bbb

2    2
1    1
0    0
dtype: int64

# 🧹  Handing missing values


1.   Dropping
2.   Imputing



# **Example 1**

In [ ]:
print(df_bbb.shape)
df_bbb.dropna(inplace=True)
print(df_bbb.shape)
print(df_bbb.isnull().sum().sort_values(ascending=False))


(1, 3)
(1, 3)
2    0
1    0
0    0
dtype: int64


# **Example 2**

In [ ]:
Arr=([2,3,7,None],[2,5,9,6],[33,3,41,6],[None,50,7,None],[None,None,31,17])
Arr= np.array(Arr)
print(Arr)
df_Arr= pd.DataFrame(Arr)
print(df_Arr)

[[2 3 7 None]
 [2 5 9 6]
 [33 3 41 6]
 [None 50 7 None]
 [None None 31 17]]
      0     1   2     3
0     2     3   7  None
1     2     5   9     6
2    33     3  41     6
3  None    50   7  None
4  None  None  31    17


In [ ]:
df_Arr=df_Arr.fillna(nan)
df_Arr

0     1   2     3
0   2.0   3.0   7   NaN
1   2.0   5.0   9   6.0
2  33.0   3.0  41   6.0
3   NaN  50.0   7   NaN
4   NaN   NaN  31  17.0

In [ ]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp = imp.fit(df_Arr)

modified = imp.transform(df_Arr)
print(modified)


[[ 2.          3.          7.          9.66666667]
 [ 2.          5.          9.          6.        ]
 [33.          3.         41.          6.        ]
 [12.33333333 50.          7.          9.66666667]
 [12.33333333 15.25       31.         17.        ]]


# **Example 3**

In [ ]:
data = [[1,2,0],
        [3,0,1],
        [5,0,0],
        [0,4,6],
        [5,0,0],
        [4,5,5]]
df_data= pd.DataFrame(data)

imputting = SimpleImputer(missing_values=0, strategy='mean')
imputting=imputting.fit(df_data)
df_data= imputting.transform(df_data)

df_data

array([[1.        , 2.        , 4.        ],
       [3.        , 3.66666667, 1.        ],
       [5.        , 3.66666667, 4.        ],
       [3.6       , 4.        , 6.        ],
       [5.        , 3.66666667, 4.        ],
       [4.        , 5.        , 5.        ]])